

name: Azure Bicep Front end Infra Deploy
on:
  workflow_dispatch:
  push:


jobs: 
  build: 
    # Build front end environment
    name: build front end
    runs-on: ubuntu-latest
    steps: 
      # Checkout code
      - uses: actions/checkout@main

      # Log into Azure
        # This describes how to generate and store azure credentials: https://learn.microsoft.com/en-us/azure/developer/github/connect-from-azure?tabs=azure-portal%2Cwindows#use-the-azure-login-action-with-a-service-principal-secret
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy Front end Bicep File
      - name: deploy
        uses: azure/arm-deploy@v1
        with:
          scope: resourcegroup
          resourceGroupName: BicepHackathonTest
          deploymentMode: incremental
          template: ./infra/frontEnd.bicep
          failOnStdErr: true

      
